version: "3.7"
services:

  server:
    image: maxkile/cpp-server:server
    ports:
      - 2425:2424
      - 2424:2424
    networks:
      - main
    command: ["./server", "2424"]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.role == manager]


  client:
    image: maxkile/cpp-server:client 
    command: ["./client", "2424","192.168.0.17"]
    networks:
      - main
    deploy:


networks:
  main:
